language: cpp
compiler: gcc
os: linux
dist: bionic

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libboost1.65-all libboost1.65-all-dev
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_SOLVER=ON ../
  - cmake --build .
  - ./solverlib/solverlib-tests && ./sudokulib/sudokulib-tests
